name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  actions: read

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  test:
    name: Test SDK
    runs-on: macos-latest
    timeout-minutes: 30
    
    strategy:
      matrix:
        ios: ['17.0', '16.0', '15.0']
        include:
          - ios: '17.0'
            device: 'iPhone 15'
          - ios: '16.0'
            device: 'iPhone 14'
          - ios: '15.0'
            device: 'iPhone 13'
    
    steps:
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Show Xcode and Swift Version
      run: |
        xcodebuild -version
        swift --version
        
    - name: Cache CocoaPods
      uses: actions/cache@v3
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
          
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod --version
        
    - name: Validate Podspec
      run: |
        pod spec lint BridgewellEventSDK.podspec --quick --allow-warnings
        
    - name: Validate Swift Package
      run: |
        echo "Skipping Swift Package validation on macOS - iOS SDK requires iOS-specific APIs"
        echo "Swift Package Manager validation will be done during iOS builds"
        
    - name: Run Tests
      run: |
        xcodebuild test \
          -workspace BridgeWellEventSDK.xcworkspace \
          -scheme BridgewellEventSDK \
          -destination 'platform=iOS Simulator,name=${{ matrix.device }},OS=${{ matrix.ios }}' \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
          
    - name: Upload Coverage Reports
      if: matrix.ios == '17.0'
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        fail_ci_if_error: false
        
  lint:
    name: Lint Code
    runs-on: macos-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install SwiftLint
      run: |
        brew install swiftlint
        
    - name: Run SwiftLint
      run: |
        swiftlint --strict
        
  validate-examples:
    name: Validate Examples
    runs-on: macos-latest
    timeout-minutes: 20
    
    steps:
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        
    - name: Validate Swift Example
      run: |
        cd Examples/SwiftExample
        pod install --repo-update
        xcodebuild build \
          -workspace SwiftExample.xcworkspace \
          -scheme SwiftExample \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
          
    - name: Validate Objective-C Example
      run: |
        cd Examples/ObjectiveCExample
        pod install --repo-update
        xcodebuild build \
          -workspace ObjectiveCExample.xcworkspace \
          -scheme ObjectiveCExample \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
