name: Publish SDK

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 0.1.0)'
        required: true
        type: string

permissions:
  contents: write
  actions: read

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  validate:
    name: Validate SDK
    runs-on: macos-latest
    timeout-minutes: 20
    
    steps:
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Show Xcode Version
      run: xcodebuild -version
      
    - name: Cache CocoaPods
      uses: actions/cache@v3
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
          
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod --version
        
    - name: Validate Podspec
      run: |
        pod spec lint BridgewellEventSDK.podspec --allow-warnings --verbose
        
    - name: Validate Swift Package
      run: |
        echo "Skipping Swift Package validation on macOS - iOS SDK requires iOS-specific APIs"
        echo "Swift Package Manager validation will be done during iOS builds"
        
  publish-cocoapods:
    name: Publish to CocoaPods
    runs-on: macos-latest
    timeout-minutes: 30
    needs: validate
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        sudo gem install cocoapods-trunk
        
    - name: Get Version
      id: version
      run: |
        if [ "${{ github.event_name }}" == "release" ]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        else
          VERSION="${{ github.event.inputs.version }}"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Publishing version: $VERSION"
        
    - name: Update Podspec Version
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        sed -i '' "s/spec.version.*=.*/spec.version      = \"$VERSION\"/" BridgewellEventSDK.podspec
        
    - name: Validate Podspec
      run: |
        pod spec lint BridgewellEventSDK.podspec --allow-warnings
        
    - name: Publish to CocoaPods Trunk
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push BridgewellEventSDK.podspec --allow-warnings
        
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [validate, publish-cocoapods]
    if: github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Get Version
      id: version
      run: |
        VERSION="${{ github.event.inputs.version }}"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Create Git Tag
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a "v$VERSION" -m "Release version $VERSION"
        git push origin "v$VERSION"
        
    - name: Generate Release Notes
      id: release_notes
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        cat > release_notes.md << EOF
        # BridgewellEventSDK v$VERSION
        
        ## Installation
        
        ### CocoaPods
        \`\`\`ruby
        pod 'BridgewellEventSDK', '~> $VERSION'
        \`\`\`
        
        ### Swift Package Manager
        \`\`\`swift
        dependencies: [
            .package(url: "https://github.com/bridgewell/BridgewellEventSDK-iOS.git", from: "$VERSION")
        ]
        \`\`\`
        
        ## What's Changed
        
        See [CHANGELOG.md](CHANGELOG.md) for detailed changes.
        
        ## Requirements
        
        - iOS 12.0+
        - Xcode 14.0+
        - Swift 5.7+
        EOF
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: BridgewellEventSDK v${{ steps.version.outputs.version }}
        body_path: release_notes.md
        draft: false
        prerelease: false
        
  notify:
    name: Notify Success
    runs-on: ubuntu-latest
    needs: [validate, publish-cocoapods]
    if: always() && (needs.validate.result == 'success' && needs.publish-cocoapods.result == 'success')
    
    steps:
    - name: Get Version
      id: version
      run: |
        if [ "${{ github.event_name }}" == "release" ]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        else
          VERSION="${{ github.event.inputs.version }}"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Success Notification
      run: |
        echo "Successfully published BridgewellEventSDK v${{ steps.version.outputs.version }}!"
        echo "CocoaPods: Available in ~15-30 minutes"
        echo "Swift Package Manager: Available immediately"
        echo "CocoaPods URL: https://cocoapods.org/pods/BridgewellEventSDK"
